name: test
on: [push]
jobs:
  test_nginx:
    runs-on: ubuntu-latest
    container:
      image: nginx:latest
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.6.0
        with:
          image_name: 'nginx:latest'
          mode: 'start'
          command: sleep 5

  rezilion:
    needs: [test_nginx]
    runs-on: ubuntu-latest
    container:
      image: rezilion/validate-ci:b63c85d0
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_DONT_RUN_REMEDIATE: true
    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.6.0
        with:
          mode: 'validate'
